[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=15780000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=15780000"

[[redirects]]
  from = "/?kategoria=fooldal&oldal=fooldal"
  to = "/?atiranyitva"
  status = 301

[[redirects]]
  status = 301
  from = "/"
  query = {kategoria = ":kategoria", oldal = ":oldal"}
  to = "/.netlify/functions/redirect/"

[[redirects]]
  status = 301
  from = "/galeria/thumbnails.php"
  query = {album = ":album"}
  to = "/.netlify/functions/redirect/"

[[redirects]]
  status = 301
  from = "/galeria/index.php"
  query = {cat = ":cat"}
  to = "/.netlify/functions/redirect/"